## Implement MLFLOW With Deep learning project (using simpleRNN)

###### Run hyperparameter sweep on a trainig script  
###### choose the best run and registerd it is as a model
###### Comapare the result of the various run in the mlflow UI
###### Deploy the model to a REST API
###### Build a container image suitable for deployment to cloud platform


In [3]:
import keras
import numpy as np 
import pandas as pd 
from hyperopt import STATUS_OK,Trials,fmin,hp,tpe
from sklearn.metrics import mean_squared_error
from sklearn.model_selection import train_test_split

import mlflow
from mlflow.models import infer_signature


In [6]:
data=pd.read_csv("../2-DLMLFLOW/data/wine-quality.csv")

In [10]:
data.head(50)


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0             7.0              0.27         0.36           20.70      0.045   
1             6.3              0.30         0.34            1.60      0.049   
2             8.1              0.28         0.40            6.90      0.050   
3             7.2              0.23         0.32            8.50      0.058   
4             7.2              0.23         0.32            8.50      0.058   
5             8.1              0.28         0.40            6.90      0.050   
6             6.2              0.32         0.16            7.00      0.045   
7             7.0              0.27         0.36           20.70      0.045   
8             6.3              0.30         0.34            1.60      0.049   
9             8.1              0.22         0.43            1.50      0.044   
10            8.1              0.27         0.41            1.45      0.033   
11            8.6              0.23         0.40            4.20      0.035   
12            7.9              0.18         0.37            1.20      0.040   
13            6.6              0.16         0.40            1.50      0.044   
14            8.3              0.42         0.62           19.25      0.040   
15            6.6              0.17         0.38            1.50      0.032   
16            6.3              0.48         0.04            1.10      0.046   
17            6.2              0.66         0.48            1.20      0.029   
18            7.4              0.34         0.42            1.10      0.033   
19            6.5              0.31         0.14            7.50      0.044   
20            6.2              0.66         0.48            1.20      0.029   
21            6.4              0.31         0.38            2.90      0.038   
22            6.8              0.26         0.42            1.70      0.049   
23            7.6              0.67         0.14            1.50      0.074   
24            6.6              0.27         0.41            1.30      0.052   
25            7.0              0.25         0.32            9.00      0.046   
26            6.9              0.24         0.35            1.00      0.052   
27            7.0              0.28         0.39            8.70      0.051   
28            7.4              0.27         0.48            1.10      0.047   
29            7.2              0.32         0.36            2.00      0.033   
30            8.5              0.24         0.39           10.40      0.044   
31            8.3              0.14         0.34            1.10      0.042   
32            7.4              0.25         0.36            2.05      0.050   
33            6.2              0.12         0.34            1.50      0.045   
34            5.8              0.27         0.20           14.95      0.044   
35            7.3              0.28         0.43            1.70      0.080   
36            6.5              0.39         0.23            5.40      0.051   
37            7.0              0.33         0.32            1.20      0.053   
38            7.3              0.24         0.39           17.95      0.057   
39            7.3              0.24         0.39           17.95      0.057   
40            6.7              0.23         0.39            2.50      0.172   
41            6.7              0.24         0.39            2.90      0.173   
42            7.0              0.31         0.26            7.40      0.069   
43            6.6              0.24         0.27            1.40      0.057   
44            6.7              0.23         0.26            1.40      0.060   
45            7.4              0.18         0.31            1.40      0.058   
46            6.2              0.45         0.26            4.40      0.063   
47            6.2              0.46         0.25            4.40      0.066   
48            7.0              0.31         0.26            7.40      0.069   
49            6.9              0.19         0.35      

In [11]:
train,test = train_test_split(data,test_size=0.25,random_state=42)

In [12]:
train


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
2835            6.3              0.25         0.22            3.30      0.048   
1157            7.8              0.30         0.29           16.85      0.054   
744             7.4              0.38         0.27            7.50      0.041   
1448            7.4              0.16         0.49            1.20      0.055   
3338            7.2              0.27         0.28           15.20      0.046   
...             ...               ...          ...             ...        ...   
4426            6.2              0.21         0.52            6.50      0.047   
466             7.0              0.14         0.32            9.00      0.039   
3092            7.6              0.27         0.52            3.20      0.043   
3772            6.3              0.24         0.29           13.70      0.035   
860             8.1              0.27         0.35            1.70      0.030   

      free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
2835                 41.0                 161.0  0.99256  3.16       0.50   
1157                 23.0                 135.0  0.99980  3.16       0.38   
744                  24.0                 160.0  0.99535  3.17       0.43   
1448                 18.0                 150.0  0.99170  3.23       0.47   
3338                  6.0                  41.0  0.99665  3.17       0.39   
...                   ...                   ...      ...   ...        ...   
4426                 28.0                 123.0  0.99418  3.22       0.49   
466                  54.0                 141.0  0.99560  3.22       0.43   
3092                 28.0                 152.0  0.99129  3.02       0.53   
3772                 53.0                 134.0  0.99567  3.17       0.38   
860                  38.0                 103.0  0.99255  3.22       0.63   

      alcohol  quality  
2835     10.5        6  
1157      9.0        6  
744      10.0        5  
1448     11.2        6  
3338     10.9        6  
...       ...      ...  
4426      9.9        6  
466       9.4        6  
3092     11.4        6  
3772     10.6        6  
860      10.4        8  

[3673 rows x 12 columns]

In [ ]:
##  dprepaire the dataset for training the model


train_x=train.drop([ "quality"],axis=1).values
train_y=train[["quality"]].values.ravel()

In [17]:
train_y

array([6, 6, 5, ..., 6, 6, 8], shape=(3673,))

In [18]:
train_x

array([[ 6.3 ,  0.25,  0.22, ...,  3.16,  0.5 , 10.5 ],
       [ 7.8 ,  0.3 ,  0.29, ...,  3.16,  0.38,  9.  ],
       [ 7.4 ,  0.38,  0.27, ...,  3.17,  0.43, 10.  ],
       ...,
       [ 7.6 ,  0.27,  0.52, ...,  3.02,  0.53, 11.4 ],
       [ 6.3 ,  0.24,  0.29, ...,  3.17,  0.38, 10.6 ],
       [ 8.1 ,  0.27,  0.35, ...,  3.22,  0.63, 10.4 ]], shape=(3673, 11))

In [ ]:
##  dprepaire the dataset for test of the model

test_x = test.drop([ "quality"],axis=1).values
test_y = test[["quality"]].values.ravel()

In [20]:
test_x

array([[ 6.        ,  0.29      ,  0.41      , ...,  3.09      ,
         0.59      , 10.96666667],
       [ 5.4       ,  0.53      ,  0.16      , ...,  3.2       ,
         0.53      , 13.2       ],
       [ 7.1       ,  0.25      ,  0.39      , ...,  3.28      ,
         0.43      , 12.2       ],
       ...,
       [ 5.9       ,  0.13      ,  0.28      , ...,  3.43      ,
         0.64      , 10.8       ],
       [ 6.8       ,  0.3       ,  0.29      , ...,  3.03      ,
         0.32      , 12.9       ],
       [ 7.4       ,  0.25      ,  0.36      , ...,  3.19      ,
         0.44      , 10.8       ]], shape=(1225, 11))

In [21]:
test_y

array([7, 8, 8, ..., 6, 7, 6], shape=(1225,))

In [23]:
## taking the train data again and spliting into validation and training 

train_x,valid_x,train_y , valid_y = train_test_split(train_x,train_y,test_size=0.20,random_state=42)

In [24]:
signature = infer_signature(train_x,train_y)

In [26]:
mean = np.mean(train_x,axis = 0)
mean

array([6.86621852e+00, 2.80377808e-01, 3.32597005e-01, 6.42164738e+00,
       4.55513955e-02, 3.53556841e+01, 1.38792376e+02, 9.94074221e-01,
       3.18919333e+00, 4.88396869e-01, 1.05005673e+01])

In [ ]:
## we nee to create our ANN model 

def train_model(params,epoch,train_x,train_y,valid_x,valid_y,test_x,test_y):
    ## model architecture 
    mean = np.mean(train_x,axis = 0)
    var = np.var(train_x,axis = 0)
    
    model = keras.Sequential(
        
        [keras.input ( train_x.shape[1])
         
         ]     
    )
    